name: Build Hybrid Mount

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29

      - name: Setup Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: aarch64-linux-android
          components: rust-src, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-multilib
          cargo install cargo-ndk --locked

      - name: Build Hybrid Mount
        run: |
          cargo xtask build --ci

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hybrid-mount-build
          path: output/*.zip
